# Generated by Django 3.1.7 on 2021-03-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='pruchaser',
            new_name='purchaser',
        ),
    ]
